CREATE TABLE GAME
(Game_ID INT AUTO_INCREMENT,
Game_Date DATE NOT NULL,
Season INT NOT NULL,
CONSTRAINT PK_GAME PRIMARY KEY(Game_ID)
);

CREATE TABLE TEAM
(Team_ID INT AUTO_INCREMENT,
Team_Name VARCHAR(50) NOT NULL,
CONSTRAINT PK_TEAM PRIMARY KEY(Team_ID)
);

CREATE TABLE PLAYER
(Player_ID INT AUTO_INCREMENT,
Player_Name VARCHAR(50) NOT NULL,
CONSTRAINT PK_PLAYER PRIMARY KEY(Player_ID)
);

CREATE TABLE DRIVE
(Drive_ID INT AUTO_INCREMENT,
Game_ID INT NOT NULL,
Game_Quarter INT NOT NULL,
Drive_Number INT NOT NULL,
-- Drive Number added to reflect datasource; not present in logical diagram
PosTeam_ID INT NOT NULL,
DefTeam_ID INT NOT NULL,
CONSTRAINT PK_DRIVE PRIMARY KEY(Drive_ID),
CONSTRAINT FK_GAME_GAME_ID FOREIGN KEY(Game_ID) REFERENCES GAME(Game_ID),
CONSTRAINT FK_TEAM_POSTEAM FOREIGN KEY(PosTeam_ID) REFERENCES TEAM(Team_ID),
CONSTRAINT FK_TEAM_DEFTEAM FOREIGN KEY(DefTeam_ID) REFERENCES TEAM(Team_ID)
);

CREATE TABLE PLAYTYPE
(Play_Type_ID INT AUTO_INCREMENT,
Play_Type VARCHAR(50) NOT NULL,
CONSTRAINT PK_PLAYTYPE PRIMARY KEY(Play_Type_ID)
);


CREATE TABLE PLAY
(Play_ID INT AUTO_INCREMENT,
Drive_ID INT NOT NULL,
Play_Number INT NOT NULL,
Play_Type_ID INT NOT NULL,
Down INT NOT NULL,
Play_Time TIME NOT NULL,
Start_Yard_Line INT NOT NULL,
Yards_Gain SMALLINT NOT NULL,
First_Down BOOLEAN NOT NULL DEFAULT FALSE,
-- First Down boolean added from dataset, not present on logical diagram
Score_Result VARCHAR(50) NULL,
CONSTRAINT PK_PLAY PRIMARY KEY(Play_ID),
CONSTRAINT FK_DRIVE_DRIVE_ID FOREIGN KEY(Drive_ID) REFERENCES DRIVE(Drive_ID),
CONSTRAINT FK_PLAYTYPE_PLAYTYPE_ID FOREIGN KEY(Play_Type_ID) REFERENCES PLAYTYPE(Play_Type_ID),
CONSTRAINT ScoreResultValues CHECK 
		(Score_Result IN ('Touchdown', 'Field_Goal', 'Extra_Point','Two-Point-Conversion','Safety' )),
CONSTRAINT DownValues CHECK (Down BETWEEN 1 AND 4),
CONSTRAINT UNIQUE_Play_Type_ID UNIQUE (Play_Type_ID)
);

CREATE TABLE PENALTIES
(Penalty_ID INT AUTO_INCREMENT,
Team_ID INT NOT NULL,
Penalty_Type VARCHAR(50) NOT NULL,
Player_ID INT NOT NULL,
Penalty_Yards INT NOT NULL,
Play_ID INT NOT NULL,
CONSTRAINT PK_PENALTIES PRIMARY KEY(Penalty_ID),
CONSTRAINT FK_TEAM_TEAM_ID FOREIGN KEY(Team_ID) REFERENCES TEAM(Team_ID),
CONSTRAINT FK_PLAYER_PLAYER_ID FOREIGN KEY(Player_ID) REFERENCES PLAYER(Player_ID),
CONSTRAINT FK_PLAY_PLAY_ID FOREIGN KEY(Play_ID) REFERENCES PLAY(Play_ID) ON DELETE CASCADE 
);
-- FK From Logical Diagram to PLAY was removed; It makes more sense to have the Penalty_ID be a FK in the PLAY table

CREATE TABLE PASSER
(Passer_ID INT AUTO_INCREMENT,
Play_ID INT NOT NULL,
Player_ID INT NOT NULL,
CONSTRAINT PK_PASSER PRIMARY KEY(Passer_ID),
CONSTRAINT FK_PASS_PLAYER_PLAYER_ID FOREIGN KEY(Player_ID) REFERENCES PLAYER(Player_ID),
CONSTRAINT FK_PASS_PLAY_PLAY_ID FOREIGN KEY(Play_ID) REFERENCES PLAY(Play_ID),
CONSTRAINT UNIQUE_Play_ID UNIQUE (Play_ID)
);

CREATE TABLE RUSHER
(RUSHER_ID INT AUTO_INCREMENT,
Play_ID INT NOT NULL,
Player_ID INT NOT NULL,
CONSTRAINT PK_RUSHER PRIMARY KEY(Rusher_ID),
CONSTRAINT FK_RUSH_PLAYER_PLAYER_ID FOREIGN KEY(Player_ID) REFERENCES PLAYER(Player_ID),
CONSTRAINT FK_RUSH_PLAY_PLAY_ID FOREIGN KEY(Play_ID) REFERENCES PLAY(Play_ID),
CONSTRAINT UNIQUE_Play_ID UNIQUE (Play_ID)
);

CREATE TABLE RECEIVER
(Receiver_ID INT AUTO_INCREMENT,
Play_ID INT NOT NULL,
Player_ID INT NOT NULL,
CONSTRAINT PK_RECEIVER PRIMARY KEY(Receiver_ID),
CONSTRAINT FK_REC_PLAYER_PLAYER_ID FOREIGN KEY(Player_ID) REFERENCES PLAYER(Player_ID),
CONSTRAINT FK_REC_PLAY_PLAY_ID FOREIGN KEY(Play_ID) REFERENCES PLAY(Play_ID),
CONSTRAINT UNIQUE_Play_ID UNIQUE (Play_ID)
);


CREATE TABLE TACKLER
(Tackler_ID INT AUTO_INCREMENT,
Play_ID INT NOT NULL,
Player_ID INT NOT NULL,
CONSTRAINT PK_TACKLER PRIMARY KEY(Tackler_ID),
CONSTRAINT FK_TACK_PLAYER_PLAYER_ID FOREIGN KEY(Player_ID) REFERENCES PLAYER(Player_ID),
CONSTRAINT FK_TACK_PLAY_PLAY_ID FOREIGN KEY(Play_ID) REFERENCES PLAY(Play_ID)
);
